"""empty message

Revision ID: 48661012b9a0
Revises: 3e0989c35c8c
Create Date: 2022-06-17 22:26:04.949060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48661012b9a0'
down_revision = '3e0989c35c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'date')
    # ### end Alembic commands ###
